name: Jekyll site CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'
        bundler-cache: true  # Enables caching to speed up builds

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libxml2-dev libxslt1-dev zlib1g-dev

    - name: Install Dart Sass Embedded
      run: |
        curl -L https://github.com/sass/dart-sass/releases/download/1.54.9/dart-sass-1.54.9-linux-x64.tar.gz -o sass.tar.gz
        tar -xzf sass.tar.gz
        sudo mv dart-sass /usr/local/bin/sass-embedded
        echo "/usr/local/bin/sass-embedded" >> $GITHUB_PATH

    - name: Configure Bundler
      run: bundle config set force_ruby_platform true  # Prevents platform-specific gem issues

    - name: Install Bundler
      run: gem install bundler

    - name: Install project dependencies
      run: bundle install

    - name: Verify Jekyll installation
      run: bundle exec jekyll -v  # Check if Jekyll is installed correctly

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
